// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyConsole.Context;

#nullable disable

namespace MyConsole.Migrations
{
    [DbContext(typeof(BooksContext))]
    partial class BooksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MyConsole.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MyConsole.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MyConsole.Entities.Title", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TitleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("MyConsole.Entities.TitleTag", b =>
                {
                    b.Property<int>("TitleTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TitleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TitleTagId");

                    b.HasIndex("TagId");

                    b.HasIndex("TitleId");

                    b.ToTable("TitlesTags", (string)null);
                });

            modelBuilder.Entity("MyConsole.Entities.Title", b =>
                {
                    b.HasOne("MyConsole.Entities.Author", "Author")
                        .WithMany("Titles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("MyConsole.Entities.TitleTag", b =>
                {
                    b.HasOne("MyConsole.Entities.Tag", "Tag")
                        .WithMany("TitleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyConsole.Entities.Title", "Title")
                        .WithMany("TitleTags")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("MyConsole.Entities.Author", b =>
                {
                    b.Navigation("Titles");
                });

            modelBuilder.Entity("MyConsole.Entities.Tag", b =>
                {
                    b.Navigation("TitleTags");
                });

            modelBuilder.Entity("MyConsole.Entities.Title", b =>
                {
                    b.Navigation("TitleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
