// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuixoWeb.Data;

#nullable disable

namespace QuixoWeb.Migrations
{
    [DbContext(typeof(QuixoDbContext))]
    [Migration("20251211193744_MakePlayerIdRequiredAgain")]
    partial class MakePlayerIdRequiredAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("QuixoWeb.Models.BoardState", b =>
                {
                    b.Property<int>("BoardStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId_FK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BoardStateId");

                    b.HasIndex("GameId_FK");

                    b.HasIndex("MoveId")
                        .IsUnique();

                    b.ToTable("BoardStates");
                });

            modelBuilder.Entity("QuixoWeb.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TotalTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("WinnerPlayerId");

                    b.HasIndex("WinnerTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("QuixoWeb.Models.Move", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CubePlacedCol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CubePlacedRow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CubeTakenCol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CubeTakenRow")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DotDirection")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("MoveId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("QuixoWeb.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("QuixoWeb.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Player1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Player2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId");

                    b.HasIndex("GameId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("QuixoWeb.Models.BoardState", b =>
                {
                    b.HasOne("QuixoWeb.Models.Game", "Game")
                        .WithMany("BoardStates")
                        .HasForeignKey("GameId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuixoWeb.Models.Move", "Move")
                        .WithOne()
                        .HasForeignKey("QuixoWeb.Models.BoardState", "MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Move");
                });

            modelBuilder.Entity("QuixoWeb.Models.Game", b =>
                {
                    b.HasOne("QuixoWeb.Models.Player", "WinnerPlayer")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuixoWeb.Models.Team", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WinnerPlayer");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("QuixoWeb.Models.Move", b =>
                {
                    b.HasOne("QuixoWeb.Models.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuixoWeb.Models.Player", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("QuixoWeb.Models.Player", b =>
                {
                    b.HasOne("QuixoWeb.Models.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("QuixoWeb.Models.Team", b =>
                {
                    b.HasOne("QuixoWeb.Models.Game", null)
                        .WithMany("Teams")
                        .HasForeignKey("GameId");

                    b.HasOne("QuixoWeb.Models.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuixoWeb.Models.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("QuixoWeb.Models.Game", b =>
                {
                    b.Navigation("BoardStates");

                    b.Navigation("Moves");

                    b.Navigation("Players");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("QuixoWeb.Models.Player", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
